allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - oxlint
  - '@oxlint/*'
  - oxfmt
  - '@oxfmt/*'
  - '@oxc-project/types'
  - oxc-parser
  - '@oxc-parser/*'
