export const rulesPrefixesForPlugins: Record<string, string> = {
  import: 'import',
  'import-x': 'import',
  jest: 'jest',
  jsdoc: 'jsdoc',
  'jsx-a11y': 'jsx-a11y',
  '@next/next': 'nextjs',
  node: 'node',
  promise: 'promise',
  react: 'react',
  'react-perf': 'react',
  '@typescript-eslint': 'typescript',
  unicorn: 'unicorn',
  vitest: 'vitest',
};
